#!/usr/bin/env python

import cmd
import re

DICT_DIR = '/home/dave/dict/dictionary'

with open('wordlist') as f:
    content = f.read()

def searchDictList(word):
    """
    search dictList.
    if not found return None
    else return the found line
    """
    text = None
    with open(DICT_DIR) as f:
        for line in f:
            if line.split(':')[0].lower() == word.lower():
                text = line
    return text


def printWord(line):
    """
    print the content
    """
    for _ in line.split(':'):
        print(_)

def complete(text):
    word = text + '.*'
    pattern = re.compile(word)
    
    match = pattern.findall(content)
    complete = match[:5]

    for _ in complete:
        _ = _.decode('utf-8')

    return complete



class HelloWorld(cmd.Cmd):
    def __init__(self):
        cmd.Cmd.__init__(self)
        self.intro = """Open Source Dictionary 1.0"""
        self.prompt = "(OSD1.0:>)"


    def do_dict(self, word):
        line = searchDictList(word)
        if line:
            printWord(line)

    def complete_dict(self, text, line, begidx, endidx):
        if not text:
            completions = ['blank', 'hello']
        else:
            if len(text) > 2:
                completions = complete(text)

        return completions

    def do_count(self, line):
        nu = 0
        for line in open(DICT_DIR):
            nu += 1
        print()
        print('(^_^): already have {} words!'.format(nu))
        print()


    def help_dict(self):
        print ("dict [word]")



    def do_EOF(self, line):
        return True

if __name__ == '__main__':
    HelloWorld().cmdloop()
